### ISSUE TITLE
Détails restants

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#3072]
- [x] Tester les overlays dans les navigateurs differents (je me demande si les capteurs d'écrans firefox s'affichent sans blur, si il y a des navigateurs où ça ne marchent pas) - testé sur firefox, chrome, safari sur Mac OSX #3471
- [x] Années à afficher : l'année dernière, l'année en cours et si la cantine à d'autre diags, les années pour ses diags #3425
- [x] Changement UI message # de satellites :
![Screenshot from 2023-10-18 15-43-15](https://github.com/betagouv/ma-cantine/assets/9282816/67d1fb06-ee9e-4ecf-9e1c-ac5308ae9fd8) 3472
- [x] Breadcrumbs to tableau de bord ? IMO want to avoid replacing link to tableau de bord with link to dev and APIs #3473
- [x] #3080
![Screenshot 2023-10-13 at 16-27-27 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/7ffb90a2-bed4-49c1-bd26-d63beb00ebb7)
- [x] Le même tag : quand le bilan est prêt pour la TD : "bilan à télédéclarer" https://github.com/betagouv/ma-cantine/pull/3099
- [x] Peaufiner le styling de ça #3082 
![Screenshot 2023-10-13 at 16-28-34 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/051b569f-7efc-42c1-a8bd-176385eb3d53)
- [x] Est-ce que ça a été remplacé ? Je le trouve pas sur le figma, mais je trouve "C'est le moment de se lancer !" là que je trouve pas dans notre code. Je trouve ça que pertinante pour l'année en cours, en on a déjà le CTA, le lien vers PurchasesHome avec l'overlay. --  https://github.com/betagouv/ma-cantine/pull/3095
![Screenshot 2023-10-13 at 17-24-16 ma cantine](https://github.com/betagouv/ma-cantine/assets/9282816/8610ea4f-58df-487a-b7c0-a245100b34dc)
- [x] EGAlim progression : hasPurchases
- [x] EGAlim progression : hasLastYearDiagnostic
- [x] Après avoir MAJ les années affichées, re-regarder la logique des CTAs Tableau de bord -> Ma progression -- https://github.com/betagouv/ma-cantine/pull/3095
- [x] Hover of cards on the « ma progression » segment should be removed when the card is not itself a link
- [x] https://github.com/betagouv/ma-cantine/issues/3066
- [x] Bug : !hasApproData don't show graph (https://github.com/betagouv/ma-cantine/pull/3150)
