### ISSUE TITLE
Tunnel gaspillage alimentaire : utiliser le nombre de couverts de la cantine

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#4333]
```[tasklist]
### Tasks
- [x] initialise payload from database (DiagnosticTunnel onMounted)
- [x] complete saveDiagnostic
- [x] complete saveAndQuit
- [ ] create synthesis page
- [x] MeasurementPeriod : initialiser nombre de couverts par jour pour une cantine
- [x] MeasurementPeriod : validation dates, la periode devrait pas être dans une autre period
```
