### ISSUE TITLE
CI : automatiser les déploiement/release/changelog avec release-please ?

### ISSUE THREAD

**Issue by raphodn** [betagouv/ma-cantine#4379]
### Quoi ?

Suite à la lecture de #4271 on pourrait mettre en place `release-please` pour automatiser (au moins une partie de) cette partie là.

https://github.com/googleapis/release-please-action

### Comment / Impact ?

1. nouvelle Github Action + paramétrage
2. Changer le nommage de nos PR pour respecter les [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
3. Squasher nos PRs au moment de les merger (réglage Github)
4. Pour déployer, merger la PR de release (qui créé un tag + maj le CHANGELOG) + rebase main

### Exemples

- https://github.com/openfoodfacts/open-prices/blob/main/CHANGELOG.md
- https://github.com/gip-inclusion/le-marche/blob/master/CHANGELOG.md
- 

### TODO

- [x] #4437 
- [x] ajouter la Github Action https://github.com/amannn/action-semantic-pull-request + configurer : https://github.com/betagouv/ma-cantine/pull/4700
- [x] ajouter la Github Action https://github.com/googleapis/release-please-action + configurer : #4701 
- [x] initialiser notre Changelog
- [ ] ajouter `improve` dans les types (pour avoir une section "Améliorations")

Bonus
- [x] #4438 
- [x] #4327 
- [x] #4385

**Comment by raphodn** [comment]
cc @Tdauvet89
