### ISSUE TITLE
Refacto CMS : basculer le modèle vers le dossier data

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#4383]
Question migration : https://medium.com/django-unleashed/transferring-a-model-with-its-data-from-one-django-app-to-another-5cdca05c7265

Changer la location de l'api pour être à /v1/api

### Todo

- [x] migrer le modèles et les données (migration)
- [x] migrer l'admin / factories / tests
- [x] migrer les viewset et filterset (edit : les garder dans le dossier `/cms`)
- [x] migrer l'API (basculer sur `/api/v1`)
- [x] s'assurer que wagtail marche :)
- [x] mettre à jour le Frontend

**Comment by raphodn** [comment]
Merci pour le lien de doc !

J'ai fait un test de serialization d'une WasteAction avec image, pour voir si ca poserait problème, looks good.
```
{
    "model": "cms.wasteaction",
    "pk": 3,
    "fields": {
        "creation_date": "2024-09-09T14:36:09.149Z",
        "modification_date": "2024-09-09T14:36:09.149Z",
        "title": "Une dernière",
        "subtitle": "",
        "description": "<p>bla bla bla</p>",
        "effort": "SMALL",
        "waste_origins": "[\"PREP\"]",
        "lead_image": 1
    }
}
```

**Comment by raphodn** [comment]
### Migration des données de demo vers prod

#### Migrer les images

1. se connecter en ssh sur demo
2. exporter en json les wagtail.images
3. récupérer chaque image en local
4. les ré-uploader dans l'ordre sur prod (via l'interface CMS)

#### Migrer les fiches

1. se connecter en ssh sur demo
2. exporter en json les wasteactions
3. modifier le json : mettre les `latest_revision_id` à null ; 
4. les ré-uploader sur prod (via ssh)
