### ISSUE TITLE
Offre végé - Réorganisation du tunnel

### ISSUE THREAD

**Issue by Tdauvet89** [betagouv/ma-cantine#4613]
Pour la prochaine campagne de TD, nous devons faire des ajustements sur le tunnel de l'offre végé. 
[Lien vers le ticket Picardie](https://www.notion.so/ETQ-lu-je-veux-savoir-la-typologie-d-offre-de-menu-dans-la-section-veg-tarienne-c5de2d4bebd045d2b570a7bfc06ab910?d=1304a08edabc8030a07e001c9f6f659d)

Ces ajustements sont nécessaire pour savoir si les établissements des secteurs SPE respectent bien la loi sur l'offre végé. Par la mm occasion, on en profite pour faire des ajustements de wording. 

**Ajustements à faire :**
Etape 2 "Options proposé aux convives" (intervertir avec l'étape 3)
![Image](https://github.com/user-attachments/assets/ed131071-b091-4141-b0b4-36e5820825bb)

-> Ajuster les wording des réponse 1 et 2.
-> Archiver la réponse 3 pour créer une nouvelle réponse à la place
Dans ma cantine, le service est en :
•  Menu unique ;
•  Choix multiple en libre-service ;
•  Choix multiple avec réservation à l’avance au jour le jour.
![Image](https://github.com/user-attachments/assets/cb86783c-d2bd-4135-979f-97558c3dbfc8)

Etape 3" Mise en place d’un menu végétarien" (intervertir avec l'étape 2)
-> Ajuster les wordings
Dans ma cantine,, j’ai mis en place un menu végétarien :
•  Non, je n’ai pas mis en place de menu végétarien ;
•  Moins d’une fois par semaine ;
•  Une fois par semaine ;
•  Plus d’une fois par semaine ;
•  De façon quotidienne.
![Image](https://github.com/user-attachments/assets/05f026af-1334-43f1-b138-929164810d79)

```[tasklist]
### Tasks
- [x] Dans le tunnel, l'étape 3 (=Options proposées aux convives) doit apparaitre en étape 2 (inverser avec "Mise en place d'un menu végétarien")
- [x] Etape "Options proposées aux convives" : ajuster les wordings
- [x] Etape "Options proposées aux convives" : archiver l'option 3 et créer une nouvelle option
- [x] Etape "Mise en place d’un menu végétarien" : ajuster les wordings
```

**Comment by Tdauvet89** [comment]
@raphodn @qloridant je vous tag sur ce ticket pour vous prévenir qu'il sera intégré dans le sprint de la semaine pro.
Il y a un point back/data a voir sur l'étape 3 avec l'archive et la création d'une nouvelle réponse

**Comment by hfroot** [comment]
Dans ma cantine, le service est en :
• Menu unique ;
• Choix multiple en libre-service ;
• Choix multiple avec réservation à l’avance au jour le jour.

@raphodn je propose que les deux derniers sont des nouvelles options, et on garde les anciennes dans la BDD

**Comment by Tdauvet89** [comment]
hello @raphodn @hfroot concernant
• Menu unique ;
• Choix multiple en libre-service ;
• Choix multiple avec réservation à l’avance au jour le jour.

j'ai vu avec Erwan, pour les établissements qui avaient précisé les bullets 2 & 3 dans les td précédentes, pour les prochaines TD, mettre par défaut demain sur • Choix multiple en libre-service.

**Comment by raphodn** [comment]
pour la nouvelle étape 2 "Options proposé aux convives", j'ai l'impression que c'est une info au niveau de la cantine plutôt non ? vs dans le tunnel "Menu végés". 

et si on la garde dans le tunnel, peut-être stocker cette info dans un tout nouveau champ (backend) plutôt ?

**Comment by raphodn** [comment]
Suite à une discussion avec @Tdauvet89 c'est en effet un "nouveau champ". Voir pour le stocker dans un endroit dédié pour faire propre :)

**Comment by raphodn** [comment]
> j'ai vu avec Erwan, pour les établissements qui avaient précisé les bullets 2 & 3 dans les td précédentes, pour les prochaines TD, mettre par défaut demain sur • Choix multiple en libre-service.

@Tdauvet89 pour les établissements qui avaient précisé le bullet 1 ("un menu végé en plat unique, sans choix"), on met par défaut en "Menu unique" ou on laisse vide ?

**Comment by Tdauvet89** [comment]
On met menu unique @raphodn

**Comment by Tdauvet89** [comment]
C'est go sur staging @raphodn 
GO pour prod 🚀
