### ISSUE TITLE
Offre végé : Changement de wording

### ISSUE THREAD

**Issue by Tdauvet89** [betagouv/ma-cantine#4616]
[Ticket picardie](https://www.notion.so/fabe4c2eba6248129d7780b10c8c0df6?v=7292cd681d954696a18da80b73156671&p=1354a08edabc803e8b8ff5135676d5e4&pm=s)

Changer les wordings `Diversification des menus` qui sont sur la plateforme par `Menus végétariens` 
Egalement renomer l'onglet de ma progression "Protéines végétales" par `Menus végétariens`

```[tasklist]
### Tasks
- [x] Tableau de bord
- [x] Ma progression
- [x] Dans le tunnel
- [x] Sur l'affiche en ligne
- [x] /modifier-ma-cantine
```

**Comment by Tdauvet89** [comment]
Hello @hfroot est-ce que tu pourrais faire ces changements de wording dans ce sprint ?

**Comment by Tdauvet89** [comment]
Testé aujourd'hui, go pour prod
